language: java
jdk:
- oraclejdk8
script: "./gradlew build curseforge"
sudo: false
branches:
  only:
  - develop
before_install:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_5aa6d8f52943_key -iv $encrypted_5aa6d8f52943_iv
  -in invtweaks.keystore.enc -out invtweaks.keystore -d; fi'
